### ISSUE TITLE
calculate_saturation_vapour_pressure_multiphase

### ISSUE THREAD

**Issue by oskrynyk** [ecmwf/thermofeel#34]
When calculating the saturation vapour pressure (calculate_saturation_vapour_pressure_multiphase) for the gridded timestamps using phases, it returns "ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()"

To handle arrays and apply vectorized operations efficiently, I suggest using saturation_improvement and, similarly, correcting moist air if pressure is available. This will improve performance when dealing with large arrays or grids of data.

def saturation_improvement(tk, phase):
    es = np.zeros_like(tk)
    y = (tk - 273.15) / (tk - 32.18)
    es[phase == 0] = 6.1121 * np.exp(17.502 * y[phase == 0])
    y = (tk - 273.15) / (tk - 0.6)
    es[phase == 1] = 6.1115 * np.exp(22.452 * y[phase == 1])

    es = 1.004 * es

    return es

**Comment by tlmquintino** [comment]
This was implemented in the version 2.0.0 but with a slightly different value for the triple point of water which was  provided as 273.15K instead of 273.16K.

**Comment by cladinapoli** [comment]
Closing as explained by @tlmquintino above
